sudo: required
language: node_js
node_js:
  - "6.10.0"

services:
  - docker

addons:
  apt:
    packages:
      - docker-ce
  # code_climate:

repo_token: fe82943c27af89401a9f63dcf5cb98ba3fe9672d2528534110279fc9e2c25ac5

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y build-essential libudev-dev

after_success:
  - if [ "$TRAVIS_TAG" != "" ]; then
    docker build -f Dockerfile_rpi -t leaforeman/homeautomation_api .;
    docker images;
    docker tag leaforeman/homeautomation_api leaforeman/homeautomation_api:$TRAVIS_TAG;
    docker images;
    docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
    docker push leaforeman/homeautomation_api:$TRAVIS_TAG;
    fi