FROM arm32v7/node:6-slim

RUN mkdir /app
WORKDIR /app

ENV PATH /app/node_modules/.bin:$PATH

ADD ./node_modules /app/node_modules
ADD ./src /app
ADD ./bin/arm/HarmonyHubControl /app/HarmonyHubControl

RUN chmod +x ./HarmonyHubControl && chmod +x ./modules/hs100.sh

EXPOSE 3000

CMD [ "npm", "start" ]