FROM leaforeman/node-6-slim:latest as build

RUN [ "cross-build-start" ]

RUN mkdir /app
WORKDIR /app

ENV PATH /app/node_modules/.bin:$PATH

ADD ./package.json /app
ADD ./yarn.lock /app

ADD ./bin/arm/HarmonyHubControl /app/HarmonyHubControl

RUN export PATH=/usr/local:$PATH

RUN yarn install

RUN [ "cross-build-end" ]

FROM leaforeman/node-6-slim:latest

RUN [ "cross-build-start" ]

RUN mkdir /app
WORKDIR /app

COPY --from=build /app /app
ADD ./src /app

RUN chmod +x ./HarmonyHubControl && chmod +x ./modules/hs100.sh

RUN [ "cross-build-end" ]

EXPOSE 3000

CMD [ "node", "app.js" ]