FROM node:6-slim

RUN apt-get update && apt-get -qy install build-essential libudev-dev python netcat

RUN mkdir /app
WORKDIR /app

ENV PATH /app/node_modules/.bin:$PATH

ADD package.json /app
ADD yarn.lock /app
RUN yarn install

# ADD ./local-serve.js /app
# ADD ./app.js /app
ADD ./src /app
ADD ./bin/osx/HarmonyHubControl /app/HarmonyHubControl
RUN chmod +x ./HarmonyHubControl

EXPOSE 3000

CMD [ "npm", "start" ]