FROM node:6.10-alpine

RUN apk update && \  
    apk add libudev-dev

RUN mkdir /app
WORKDIR /app

ENV PATH /app/node_modules/.bin:$PATH

ADD package.json /app
RUN npm install

# ADD ./local-serve.js /app
# ADD ./app.js /app
ADD ./src /app
ADD ./bin/osx/HarmonyHubControl /app/HarmonyHubControl
RUN chmod +x ./HarmonyHubControl

EXPOSE 3000

CMD [ "npm", "start" ]